Rename to readydocker and change mux files

diff --git a/scripts/readydocker b/scripts/readydocker
--- a/scripts/readydocker
+++ b/scripts/readydocker
@@ -1,20 +1,33 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+###############################################################
+# Ready Docker
+###############################################################
+#
 # Ensure Docker.app is running and ready to bring containers up
-# Designed to be used in environments where you want to bring up
-# a container without human interaction.
+# Designed to be used in environments where you want to bring
+# up a container without human interaction.
 #
 # Example Usage:
-# dockerwait && docker-compose up -d
+#
+# readydocker && docker-compose up -d
+#
+# Expectations:
+#
+# - Docker should be located at /Applications/Docker.app
+# - /tmp/ should be writable
+# - docker command should be on $PATH
 
 ###############################################################
 # Runs when the script exits but only if lock has been obtained
 ###############################################################
 exit_script() {
-    if [[ -e /tmp/dockerwait.lock ]]; then
-        echo "Removing /tmp/dockerwait.lock"
-        rm /tmp/dockerwait.lock
+    if [[ -e /tmp/readydocker.lock ]]; then
+        echo "Removing /tmp/readydocker.lock"
+        rm /tmp/readydocker.lock
     fi
-    trap - SIGINT SIGTERM # clear the trap
+    # Clear trap
+    trap - SIGINT SIGTERM
     kill -- -$$
 }
 
@@ -27,16 +40,16 @@ is_docker_ready() {
 }
 
 # Wait until another process has released the lock
-while [[ -e /tmp/dockerwait.lock ]]; do
-    echo "Waiting for dockerwait to release lock"
+while [[ -e /tmp/readydocker.lock ]]; do
+    echo "Waiting for readydocker to release lock"
     sleep 1
 done
 
-# Add a lock to be respectful with concurrent dockerwait commands
+# Adds lock to be work with concurrent readydocker commands
 echo "Obtaining /tmp/docker.lock"
-touch /tmp/dockerwait.lock
+touch /tmp/readydocker.lock
 
-# We need to register clean up if we are SIGINT/TERM'd
+# Register clean up if we are SIGINT/TERM'd
 trap exit_script SIGINT SIGTERM
 
 echo "Checking if docker is running"
@@ -54,5 +67,5 @@ else
 fi
 
 # Remove the lock
-echo "Removing /tmp/dockerwait.lock"
-rm /tmp/dockerwait.lock
+echo "Removing /tmp/readydocker.lock"
+rm /tmp/readydocker.lock
